version: '3.1'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    networks:
      - app-tier
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=localhost
      - REDIS_SENTINEL_RESOLVE_HOSTNAMES=yes
    ports:
      - '26379:26379'
    networks:
      - app-tier
  oracle-db:
    image: 'container-registry.oracle.com/database/enterprise:19.3.0.0'
    container_name: 'oracle19c'
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_CHARACTERSET=WE8ISO8859P15
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=1234562024
      - ORACLE_MEM=2000
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    ports:
      - '1521:1521'
      - '5500:5500'
    healthcheck:
      test: [ "CMD", "sqlplus", "-L", "sys/1234562024//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-backup: